#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
language: scala
install: true
jdk:
  - openjdk8
scala:
  - 2.11.8

# the secure configurations in env: section is for BINTRAY_USER=<USER> and BINTRAY_KEY=<KEY> properties
# which will be used for publishing artifacts to snapshot repository
env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx128m"
    - ORG_GRADLE_PROJECT_logOutput=true

sudo: required

services:
  - docker

cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"
  - "$HOME/.m2"

stages:
  - name: build
  - name: snapshot
    # master or release branch
    if: (branch = master OR branch =~ /^r[0-9]\.[0-9][\S]*/) AND NOT (type = pull_request)

jobs:
  include:
    - stage: build
      script: ./gradlew clean build
        after_success: bash <(curl -s https://codecov.io/bash) -t 9c42ff48-d98f-4444-af05-cf734aa1dbd0

    - stage: snapshot
      script: ./gradlew publishToRepo -PpublishUrl=jcenterSnapshot -PpublishUsername=$BINTRAY_USER -PpublishPassword=$BINTRAY_KEY


notifications:
  email:
  - claudio.fahey@dell.com
  - thejas.vidyasagar@dell.com
